[phases.setup]
nixPkgs = ['nodejs_20', 'npm-9_x', 'tesseract4', 'poppler_utils']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['echo "No build step needed"']

[start]
cmd = 'node server.js'
